FROM ubuntu:20.04

RUN apt-get update && apt-get upgrade

# Install mysql-server
RUN apt-get install -y wget mysql-server

# Install golang
# M1 / ARM
# RUN wget -c https://dl.google.com/go/go1.17.1.linux-arm64.tar.gz -O - | sudo tar -xz -C /usr/local
# AMD64 
RUN wget -c https://dl.google.com/go/go1.17.1.linux-amd64.tar.gz -O - | sudo tar -xz -C /usr/local


EXPOSE 3306
EXPOSE 8000


